# CMake generated Testfile for 
# Source directory: /Users/manoj/Documents/c++/code
# Build directory: /Users/manoj/Documents/c++/code/build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[how-many-degrees]=] "how-many-degrees")
set_tests_properties([=[how-many-degrees]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;33;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[string-theory]=] "string-theory")
set_tests_properties([=[string-theory]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;34;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[counting-copies]=] "counting-copies")
set_tests_properties([=[counting-copies]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;35;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[hack-the-planet]=] "hack-the-planet")
set_tests_properties([=[hack-the-planet]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;36;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[going-global]=] "going-global")
set_tests_properties([=[going-global]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;37;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[a-destructive-relationship]=] "a-destructive-relationship")
set_tests_properties([=[a-destructive-relationship]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;38;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[whos-up-first]=] "whos-up-first")
set_tests_properties([=[whos-up-first]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;39;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[all-good-things-must-come-to-an-end]=] "all-good-things-must-come-to-an-end")
set_tests_properties([=[all-good-things-must-come-to-an-end]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;40;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[will-it-move]=] "will-it-move")
set_tests_properties([=[will-it-move]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;41;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[a-strange-assignment]=] "a-strange-assignment")
set_tests_properties([=[a-strange-assignment]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;42;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[whats-the-time-of-death]=] "whats-the-time-of-death")
set_tests_properties([=[whats-the-time-of-death]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;43;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[a-false-start]=] "a-false-start")
set_tests_properties([=[a-false-start]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;44;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[a-constant-struggle]=] "a-constant-struggle")
set_tests_properties([=[a-constant-struggle]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;45;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[aristotles-sum-of-parts]=] "aristotles-sum-of-parts")
set_tests_properties([=[aristotles-sum-of-parts]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;46;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[back-from-the-future]=] "back-from-the-future")
set_tests_properties([=[back-from-the-future]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;47;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[an-overloaded-container]=] "an-overloaded-container")
set_tests_properties([=[an-overloaded-container]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;49;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[a-strong-point]=] "a-strong-point")
set_tests_properties([=[a-strong-point]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;50;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[moving-out]=] "moving-out")
set_tests_properties([=[moving-out]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;51;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[a-little-sum-thing]=] "a-little-sum-thing")
set_tests_properties([=[a-little-sum-thing]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;52;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[monsters-on-the-move]=] "monsters-on-the-move")
set_tests_properties([=[monsters-on-the-move]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;53;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[sizing-up-some-characters]=] "sizing-up-some-characters")
set_tests_properties([=[sizing-up-some-characters]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;54;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[the-phantom-spaceship]=] "the-phantom-spaceship")
set_tests_properties([=[the-phantom-spaceship]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;55;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[off-to-a-good-start]=] "off-to-a-good-start")
set_tests_properties([=[off-to-a-good-start]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;56;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[a-specialized-string-theory]=] "a-specialized-string-theory")
set_tests_properties([=[a-specialized-string-theory]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;57;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
add_test([=[weakly-typed-strongly-puzzling]=] "weakly-typed-strongly-puzzling")
set_tests_properties([=[weakly-typed-strongly-puzzling]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/manoj/Documents/c++/code/CMakeLists.txt;23;add_test;/Users/manoj/Documents/c++/code/CMakeLists.txt;58;add_puzzle;/Users/manoj/Documents/c++/code/CMakeLists.txt;0;")
subdirs("examples")
